version: "3.7"
services:
  db:
    image: mysql:5.7 # 최신 버전의 MySQL 이미지를 사용
    restart: always # Docker가 시작될 때마다 MySQL 컨테이너를 자동으로 시작
    container_name: mysql-server
    environment: # MySQL 서버의 환경 변수를 설정
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports: # 호스트의 3306 포트와 컨테이너의 3306 포트를 연결합니다.
      - "3306:3306"
    volumes: # mysql-data 볼륨을 컨테이너의 /var/lib/mysql 디렉토리에 마운트
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
